# Generated by Django 6.0.2 on 2026-06-24 12:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0002_feedback_service_feedback_status_feedback_updated_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='feedback',
            name='feedback_fe_status_212662_idx',
        ),
        migrations.AddIndex(
            model_name='feedback',
            index=models.Index(fields=['-created_at'], name='feedback_fe_created_a1f280_idx'),
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='service',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='status',
        ),
    ]
