# Generated by Django 6.0.2 on 2026-06-29 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0004_faqcategory_faqitem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feedback',
            options={'ordering': ['-created_at'], 'verbose_name': 'Feedback', 'verbose_name_plural': 'Feedback Emails'},
        ),
    ]
