# Generated by Django 6.0.2 on 2026-07-10 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0005_alter_feedback_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='faqcategory',
            options={'ordering': ('sort_order', 'title'), 'verbose_name': 'FAQ Category', 'verbose_name_plural': 'FAQ Categories'},
        ),
    ]
