# Generated by Django 6.0.2 on 2026-02-24 03:35

import apps.accounts_core.managers
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', apps.accounts_core.managers.UserManager()),
            ],
        ),
    ]
