# Generated by Django 6.0.2 on 2026-03-02 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_core', '0002_alter_user_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('Coach', 'Coach')], max_length=255, null=True, verbose_name='Role'),
        ),
    ]
