# Generated by Django 6.0.2 on 2026-03-02 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_core', '0004_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('Coach', 'Coach'), ('User', 'User')], max_length=255, null=True, verbose_name='Role'),
        ),
    ]
