# Generated by Django 6.0.2 on 2026-03-02 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_core', '0005_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='coach_status',
            field=models.CharField(blank=True, choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], max_length=20, null=True),
        ),
    ]
