# Generated by Django 6.0.2 on 2026-03-02 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_core', '0006_user_coach_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('Coach', 'Coach'), ('User', 'User')], max_length=20, null=True),
        ),
    ]
