# Generated by Django 6.0.2 on 2026-03-03 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_core', '0009_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('Coach', 'Coach'), ('Student', 'Student'), ('Nutrition', 'Nutrition'), ('Psychology', 'Psychology')], max_length=20, null=True),
        ),
    ]
