# Generated by Django 6.0.2 on 2026-04-01 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_core', '0010_alter_user_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='telegram_id',
        ),
        migrations.AddField(
            model_name='user',
            name='telegram_chat_id',
            field=models.CharField(blank=True, help_text='Особистий Telegram-канал тренера для отримання файлів клієнтів.', max_length=50, null=True),
        ),
    ]
