# Generated by Django 6.0.2 on 2026-04-04 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_core', '0012_coachprofile_studentprofile_user_avatar_user_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='country',
            field=models.CharField(blank=True, help_text='Select your country of residence to adapt timezones and regional settings.', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='currency',
            field=models.CharField(blank=True, help_text='Choose the primary currency for displaying prices and processing payments.', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='language',
            field=models.CharField(blank=True, help_text='Choose your language', max_length=50, null=True),
        ),
    ]
