# Generated by Django 6.0.2 on 2026-05-12 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_core', '0013_alter_user_country_alter_user_currency_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='company',
            field=models.CharField(blank=True, help_text='Choose your company', max_length=50, null=True),
        ),
    ]
