# Generated by Django 6.0.2 on 2026-05-12 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_core', '0014_user_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, help_text='Choose your phone number', max_length=20, null=True),
        ),
    ]
