# Generated by Django 6.0.2 on 2026-05-12 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_core', '0015_user_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='company_site',
            field=models.CharField(blank=True, help_text='Choose your company site', max_length=50, null=True),
        ),
    ]
