# Generated by Django 6.0.2 on 2026-05-12 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_core', '0016_user_company_site'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='timezone',
            field=models.CharField(blank=True, help_text='Choose your timezone', max_length=50, null=True),
        ),
    ]
