# Generated by Django 6.0.2 on 2026-05-12 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_core', '0017_user_timezone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='timezone',
            field=models.CharField(blank=True, help_text='Choose your timezone', max_length=100, null=True),
        ),
    ]
