# Generated by Django 6.0.2 on 2026-06-26 14:51

import apps.accounts_core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_core', '0018_alter_user_timezone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.FileField(blank=True, help_text='Upload your avatar to this personal dashboard.', null=True, upload_to='avatar', validators=[apps.accounts_core.validators.validate_avatar_size]),
        ),
    ]
