# Generated by Django 6.0.2 on 2026-06-29 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_core', '0019_alter_user_avatar'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CoachProfile',
        ),
        migrations.DeleteModel(
            name='StudentProfile',
        ),
    ]
