# Generated by Django 6.0.2 on 2026-07-10 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_core', '0020_delete_coachprofile_delete_studentprofile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='coach_status',
            new_name='user_status',
        ),
    ]
