# Generated by Django 6.0.2 on 2026-07-23 10:22

import apps.accounts_core.utils
import apps.accounts_core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_core', '0021_rename_coach_status_user_user_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.FileField(blank=True, help_text='Upload your avatar to this personal dashboard.', null=True, upload_to=apps.accounts_core.utils._user_avatar_upload_path, validators=[apps.accounts_core.validators.validate_avatar_size]),
        ),
    ]
