# Generated by Django 6.0.2 on 2026-03-16 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consulting', '0002_alter_request_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='requeststatushistory',
            options={'verbose_name': 'Request Status History', 'verbose_name_plural': 'Request Status Histories'},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'verbose_name': 'Service', 'verbose_name_plural': 'Services'},
        ),
    ]
