# Generated by Django 6.0.2 on 2026-03-17 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consulting', '0003_alter_requeststatushistory_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='media',
            options={'verbose_name': 'Media', 'verbose_name_plural': 'Medias'},
        ),
    ]
