# Generated by Django 6.0.2 on 2026-04-01 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consulting', '0004_alter_media_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='telegram_chat_id',
            field=models.CharField(blank=True, help_text='ID Telegram-каналу для файлів цієї послуги (напр. -100123456789)', max_length=50, null=True),
        ),
    ]
