# Generated by Django 6.0.2 on 2026-04-01 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consulting', '0005_service_telegram_chat_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='telegram_chat_id',
        ),
    ]
