# Generated by Django 6.0.2 on 2026-04-25 13:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consulting', '0006_remove_service_telegram_chat_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='specialist',
        ),
        migrations.AddField(
            model_name='request',
            name='assigned_specialist',
            field=models.ForeignKey(blank=True, help_text='The specific coach assigned to this request. Empty until accepted.', limit_choices_to={'role': 'Coach'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='request',
            name='specialty_needed',
            field=models.CharField(choices=[('TENNIS', 'Tennis Coach'), ('NUTRITION', 'Nutritionist'), ('PSYCHOLOGY', 'Psychologist')], default='TENNIS', help_text='The type of specialist required for this request.', max_length=20),
        ),
    ]
