# Generated by Django 6.0.2 on 2026-06-04 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consulting', '0007_remove_request_specialist_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='report',
            options={'ordering': ['-created_at'], 'verbose_name': 'Report', 'verbose_name_plural': 'Reports'},
        ),
        migrations.AddField(
            model_name='report',
            name='action_plan',
            field=models.TextField(blank=True, verbose_name='2–4 Week Action Plan'),
        ),
        migrations.AddField(
            model_name='report',
            name='overall_assessment',
            field=models.TextField(blank=True, verbose_name='Overall Assessment'),
        ),
        migrations.AddField(
            model_name='report',
            name='priority_1_drill',
            field=models.TextField(blank=True, verbose_name='Recommended drill (1)'),
        ),
        migrations.AddField(
            model_name='report',
            name='priority_1_issue',
            field=models.CharField(blank=True, max_length=255, verbose_name='Priority 1 Issue'),
        ),
        migrations.AddField(
            model_name='report',
            name='priority_1_why',
            field=models.TextField(blank=True, verbose_name='Why it matters (1)'),
        ),
        migrations.AddField(
            model_name='report',
            name='priority_2_drill',
            field=models.TextField(blank=True, verbose_name='Recommended drill (2)'),
        ),
        migrations.AddField(
            model_name='report',
            name='priority_2_issue',
            field=models.CharField(blank=True, max_length=255, verbose_name='Priority 2 Issue'),
        ),
        migrations.AddField(
            model_name='report',
            name='priority_2_why',
            field=models.TextField(blank=True, verbose_name='Why it matters (2)'),
        ),
        migrations.AddField(
            model_name='report',
            name='priority_3_drill',
            field=models.TextField(blank=True, verbose_name='Recommended drill (3)'),
        ),
        migrations.AddField(
            model_name='report',
            name='priority_3_issue',
            field=models.CharField(blank=True, max_length=255, verbose_name='Priority 3 Issue'),
        ),
        migrations.AddField(
            model_name='report',
            name='priority_3_why',
            field=models.TextField(blank=True, verbose_name='Why it matters (3)'),
        ),
        migrations.AddField(
            model_name='report',
            name='strength_1',
            field=models.CharField(blank=True, max_length=255, verbose_name='Key Strength 1'),
        ),
        migrations.AddField(
            model_name='report',
            name='strength_2',
            field=models.CharField(blank=True, max_length=255, verbose_name='Key Strength 2'),
        ),
        migrations.AddField(
            model_name='report',
            name='strength_3',
            field=models.CharField(blank=True, max_length=255, verbose_name='Key Strength 3'),
        ),
        migrations.AlterField(
            model_name='report',
            name='external_link',
            field=models.URLField(blank=True, verbose_name='External Link'),
        ),
        migrations.AlterField(
            model_name='report',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to='reports/', verbose_name='Attached PDF'),
        ),
        migrations.AlterField(
            model_name='report',
            name='text',
            field=models.TextField(blank=True, help_text="Use this for any general feedback that doesn't fit the structured analysis.", verbose_name='Additional Comments / General Text'),
        ),
    ]
