# Generated by Django 6.0.2 on 2026-06-26 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consulting', '0008_alter_report_options_report_action_plan_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
