# Generated by Django 6.0.2 on 2026-06-27 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consulting', '0009_alter_media_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_key', models.CharField(db_index=True, max_length=500, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'verbose_name': 'Pending Upload',
                'verbose_name_plural': 'Pending Uploads',
            },
        ),
    ]
