# Generated by Django 6.0.2 on 2026-07-10 12:27

import apps.consulting.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consulting', '0010_pendingupload'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='requests/', validators=[apps.consulting.validators.validate_media_file]),
        ),
        migrations.CreateModel(
            name='NutritionIntake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='Full Name')),
                ('date_of_birth', models.DateField(verbose_name='Date of Birth')),
                ('age', models.PositiveIntegerField(verbose_name='Age at the time of appeal')),
                ('weight', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Weight (kg)')),
                ('height', models.PositiveIntegerField(verbose_name='Height (cm)')),
                ('handedness', models.CharField(choices=[('Right', 'Right-handed'), ('Left', 'Left-handed'), ('Ambidextrous', 'Ambidextrous')], default='Right', max_length=15, verbose_name='Handedness')),
                ('language', models.CharField(max_length=100, verbose_name='Preferred Language')),
                ('whatsapp_number', models.CharField(max_length=30, verbose_name='WhatsApp Contact Number')),
                ('complaints', models.TextField(verbose_name='Complaints at the time of Appeal')),
                ('chronic_diseases', models.TextField(blank=True, null=True, verbose_name='Chronic Diseases')),
                ('medications_and_vitamins', models.TextField(blank=True, null=True, verbose_name='Constant intake of medication, vitamins, sport nutrition')),
                ('operations', models.TextField(blank=True, null=True, verbose_name='Operations')),
                ('traumas', models.TextField(blank=True, null=True, verbose_name='Traumas')),
                ('allergies', models.TextField(blank=True, null=True, verbose_name='Allergies')),
                ('attachments', models.FileField(blank=True, null=True, upload_to='nutrition/intakes/%Y/%m/', validators=[apps.consulting.validators.validate_media_file], verbose_name='Analyses and/or diagnostic papers')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nutrition_intakes', to=settings.AUTH_USER_MODEL, verbose_name='Student')),
            ],
            options={
                'verbose_name': 'Nutrition Intake',
                'verbose_name_plural': 'Nutrition Intakes',
                'ordering': ['-created_at'],
            },
        ),
    ]
