# Generated by Django 6.0.2 on 2026-07-10 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consulting', '0011_alter_media_file_nutritionintake'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='requests/'),
        ),
    ]
