# Generated by Django 6.0.2 on 2026-07-10 13:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consulting', '0012_alter_media_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='nutritionintake',
            name='request',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nutrition_intake', to='consulting.request', verbose_name='Associated Request'),
        ),
    ]
