# Generated by Django 6.0.2 on 2026-07-10 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consulting', '0013_nutritionintake_request'),
    ]

    operations = [
        migrations.RenameField(
            model_name='media',
            old_name='uploaded_at',
            new_name='created_at',
        ),
    ]
