# Generated by Django 6.0.2 on 2026-07-10 17:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consulting', '0014_rename_uploaded_at_media_created_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='assigned_specialist',
            field=models.ForeignKey(blank=True, help_text='The specific coach assigned to this request. Empty until accepted.', limit_choices_to=models.Q(('role', 'Student'), _negated=True), null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_requests', to=settings.AUTH_USER_MODEL),
        ),
    ]
