# Generated by Django 6.0.2 on 2026-07-13 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consulting', '0016_alter_request_assigned_specialist'),
    ]

    operations = [
        migrations.AddField(
            model_name='nutritionintake',
            name='appointment_date',
            field=models.DateTimeField(blank=True, help_text='Scheduled date and time for the consultation.', null=True, verbose_name='Appointment Date & Time'),
        ),
    ]
