# Generated by Django 6.0.2 on 2026-07-14 12:37

import apps.consulting.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consulting', '0017_nutritionintake_appointment_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='requests/tennis/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='nutritionintake',
            name='attachments',
            field=models.FileField(blank=True, null=True, upload_to='requests/nutrition/%Y/%m/', validators=[apps.consulting.validators.validate_media_file], verbose_name='Analyses and/or diagnostic papers'),
        ),
        migrations.AlterField(
            model_name='report',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to='reports/coach/%Y/%m/', verbose_name='Attached PDF'),
        ),
    ]
