# Generated by Django 6.0.2 on 2026-07-22 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consulting', '0018_alter_media_file_alter_nutritionintake_attachments_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='nutritionintake',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='End Date'),
        ),
        migrations.AddField(
            model_name='nutritionintake',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Start Date'),
        ),
    ]
