# Generated by Django 6.0.2 on 2026-07-22 13:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consulting', '0019_nutritionintake_end_date_nutritionintake_start_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='nutritionintake',
            name='assigned_specialist',
            field=models.ForeignKey(blank=True, help_text='The specific coach/specialist assigned to this request. Empty until accepted.', limit_choices_to={'role__in': ['Coach', 'Nutrition', 'Psychology']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_nutrition_intakes', to=settings.AUTH_USER_MODEL, verbose_name='Assigned Specialist'),
        ),
    ]
