# Generated by Django 6.0.2 on 2026-07-22 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consulting', '0020_nutritionintake_assigned_specialist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nutritionintake',
            name='assigned_specialist',
        ),
    ]
