# Generated by Django 6.0.2 on 2026-07-22 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consulting', '0021_remove_nutritionintake_assigned_specialist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nutritionintake',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='End Date'),
        ),
        migrations.AlterField(
            model_name='nutritionintake',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Start Date'),
        ),
    ]
