# Generated by Django 6.0.2 on 2026-07-22 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consulting', '0022_alter_nutritionintake_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='is_viwed',
            field=models.BooleanField(default=False),
        ),
    ]
