# Generated by Django 6.0.2 on 2026-07-22 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consulting', '0023_request_is_viwed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='request',
            old_name='is_viwed',
            new_name='is_viewed',
        ),
    ]
