# Generated by Django 6.0.2 on 2026-07-29 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consulting', '0024_rename_is_viwed_request_is_viewed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nutritionintake',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='nutritionintake',
            name='start_date',
        ),
    ]
