# Generated by Django 6.0.2 on 2026-08-06 07:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consulting', '0025_remove_nutritionintake_end_date_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PsychologyIntake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_date', models.DateTimeField(help_text='Scheduled date and time for the psychology consultation.', verbose_name='Appointment Date & Time')),
                ('whatsapp_number', models.CharField(help_text='Crucial for online therapy sessions.', max_length=30, verbose_name='Contact Number (WhatsApp/Telegram)')),
                ('primary_concern', models.TextField(blank=True, help_text='Describe what bothers the client right now.', null=True, verbose_name='Primary Concern / Reason for seeking help')),
                ('previous_therapy', models.BooleanField(default=False, verbose_name='Previous Therapy Experience')),
                ('psychiatric_medications', models.TextField(blank=True, help_text='Antidepressants, anxiolytics, etc. (if any).', null=True, verbose_name='Current Psychiatric Medications')),
                ('crisis_state', models.BooleanField(default=False, help_text='Flag for urgent attention (e.g. severe depression, panic attacks).', verbose_name='Is the client in a crisis state?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('request', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='psychology_intake', to='consulting.request', verbose_name='Associated Request')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='psychology_intakes', to=settings.AUTH_USER_MODEL, verbose_name='Client')),
            ],
            options={
                'verbose_name': 'Psychology Intake',
                'verbose_name_plural': 'Psychology Intakes',
                'ordering': ['-created_at'],
            },
        ),
    ]
