# Generated by Django 6.0.2 on 2026-08-20 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consulting', '0026_psychologyintake'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='specialty',
            field=models.CharField(choices=[('TENNIS', 'Tennis Coach'), ('NUTRITION', 'Nutritionist'), ('PSYCHOLOGY', 'Psychologist')], default='TENNIS', max_length=20, verbose_name='Specialty Domain'),
        ),
        migrations.AlterField(
            model_name='service',
            name='service_type',
            field=models.CharField(choices=[('short', 'Video Analysis Short'), ('long', 'Video Analysis Long'), ('nutr_intro', 'Introductory Session'), ('nutr_basic', 'Basic Support'), ('nutr_in_depth', 'In-Depth Coaching & Support'), ('psych_discover', 'Discover'), ('psych_develop', 'Develop'), ('psych_transform', 'Transform')], max_length=50),
        ),
    ]
