# Generated by Django 6.0.2 on 2026-08-20 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consulting', '0027_service_specialty_alter_service_service_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='requests/tennis/%Y/%m/%d/'),
        ),
    ]
