# Generated by Django 6.0.2 on 2026-08-20 17:07

import apps.consulting.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consulting', '0028_alter_media_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nutritionintake',
            name='attachments',
            field=models.FileField(blank=True, null=True, upload_to='requests/nutrition/%Y/%m/%d/', validators=[apps.consulting.validators.validate_media_file], verbose_name='Analyses and/or diagnostic papers'),
        ),
    ]
