# Generated by Django 6.0.2 on 2026-08-20 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consulting', '0029_alter_nutritionintake_attachments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nutritionintake',
            name='attachments',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Analyses and/or diagnostic papers'),
        ),
    ]
