# Generated by Django 6.0.2 on 2026-08-20 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consulting', '0030_alter_nutritionintake_attachments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nutritionintake',
            name='attachments',
            field=models.FileField(blank=True, null=True, upload_to='requests/nutrition/%Y/%m/%d/', verbose_name='Analyses and/or diagnostic papers'),
        ),
    ]
