# Generated by Django 6.0.2 on 2026-08-22 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consulting', '0031_alter_nutritionintake_attachments'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='file_size_bytes',
            field=models.PositiveBigIntegerField(blank=True, help_text='Stored locally to prevent N+1 API calls to cloud storage.', null=True, verbose_name='File size in bytes'),
        ),
        migrations.AddField(
            model_name='nutritionintake',
            name='file_size_bytes',
            field=models.PositiveBigIntegerField(blank=True, help_text='Stored locally to prevent N+1 API calls to cloud storage.', null=True, verbose_name='File size in bytes'),
        ),
    ]
