# Generated by Django 6.0.2 on 2026-08-22 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consulting', '0032_media_file_size_bytes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nutritionintake',
            name='date_of_birth',
        ),
    ]
