# Generated by Django 6.0.2 on 2026-08-22 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consulting', '0033_remove_nutritionintake_date_of_birth'),
    ]

    operations = [
        migrations.AddField(
            model_name='nutritionintake',
            name='height_unit',
            field=models.CharField(choices=[('cm', 'cm'), ('in', 'in')], default='cm', max_length=5, verbose_name='Height Unit'),
        ),
        migrations.AddField(
            model_name='nutritionintake',
            name='weight_unit',
            field=models.CharField(choices=[('kg', 'kg'), ('lbs', 'lbs')], default='kg', max_length=5, verbose_name='Weight Unit'),
        ),
        migrations.AlterField(
            model_name='nutritionintake',
            name='height',
            field=models.PositiveIntegerField(verbose_name='Height'),
        ),
        migrations.AlterField(
            model_name='nutritionintake',
            name='weight',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Weight'),
        ),
    ]
