COUNTRIES_DATA = [
    {"code": "AF", "name": "Afghanistan", "flag": "afghanistan.svg"},
    {"code": "AX", "name": "Aland Islands", "flag": "aland-islands.svg"},
    {"code": "AL", "name": "Albania", "flag": "albania.svg"},
    {"code": "DZ", "name": "Algeria", "flag": "algeria.svg"},
    {"code": "AS", "name": "American Samoa", "flag": "american-samoa.svg"},
    {"code": "AD", "name": "Andorra", "flag": "andorra.svg"},
    {"code": "AO", "name": "Angola", "flag": "angola.svg"},
    {"code": "AI", "name": "Anguilla", "flag": "anguilla.svg"},
    {"code": "AG", "name": "Antigua and Barbuda", "flag": "antigua-and-barbuda.svg"},
    {"code": "AR", "name": "Argentina", "flag": "argentina.svg"},
    {"code": "AM", "name": "Armenia", "flag": "armenia.svg"},
    {"code": "AW", "name": "Aruba", "flag": "aruba.svg"},
    {"code": "AU", "name": "Australia", "flag": "australia.svg"},
    {"code": "AT", "name": "Austria", "flag": "austria.svg"},
    {"code": "AZ", "name": "Azerbaijan", "flag": "azerbaijan.svg"},
    {"code": "BS", "name": "Bahamas", "flag": "bahamas.svg"},
    {"code": "BH", "name": "Bahrain", "flag": "bahrain.svg"},
    {"code": "BD", "name": "Bangladesh", "flag": "bangladesh.svg"},
    {"code": "BB", "name": "Barbados", "flag": "barbados.svg"},
    {"code": "BY", "name": "Belarus", "flag": "belarus.svg"},
    {"code": "BE", "name": "Belgium", "flag": "belgium.svg"},
    {"code": "BZ", "name": "Belize", "flag": "belize.svg"},
    {"code": "BJ", "name": "Benin", "flag": "benin.svg"},
    {"code": "BM", "name": "Bermuda", "flag": "bermuda.svg"},
    {"code": "BT", "name": "Bhutan", "flag": "bhutan.svg"},
    {"code": "BO", "name": "Bolivia, Plurinational State of", "flag": "bolivia.svg"},
    {"code": "BQ", "name": "Bonaire, Sint Eustatius and Saba", "flag": "bonaire.svg"},
    {"code": "BA", "name": "Bosnia and Herzegovina", "flag": "bosnia-and-herzegovina.svg"},
    {"code": "BW", "name": "Botswana", "flag": "botswana.svg"},
    {"code": "BR", "name": "Brazil", "flag": "brazil.svg"},
    {"code": "IO", "name": "British Indian Ocean Territory", "flag": "british-indian-ocean-territory.svg"},
    {"code": "BN", "name": "Brunei Darussalam", "flag": "brunei.svg"},
    {"code": "BG", "name": "Bulgaria", "flag": "bulgaria.svg"},
    {"code": "BF", "name": "Burkina Faso", "flag": "burkina-faso.svg"},
    {"code": "BI", "name": "Burundi", "flag": "burundi.svg"},
    {"code": "KH", "name": "Cambodia", "flag": "cambodia.svg"},
    {"code": "CM", "name": "Cameroon", "flag": "cameroon.svg"},
    {"code": "CA", "name": "Canada", "flag": "canada.svg"},
    {"code": "CV", "name": "Cape Verde", "flag": "cape-verde.svg"},
    {"code": "KY", "name": "Cayman Islands", "flag": "cayman-islands.svg"},
    {"code": "CF", "name": "Central African Republic", "flag": "central-african-republic.svg"},
    {"code": "TD", "name": "Chad", "flag": "chad.svg"},
    {"code": "CL", "name": "Chile", "flag": "chile.svg"},
    {"code": "CN", "name": "China", "flag": "china.svg"},
    {"code": "CX", "name": "Christmas Island", "flag": "christmas-island.svg"},
    {"code": "CC", "name": "Cocos (Keeling) Islands", "flag": "cocos-island.svg"},
    {"code": "CO", "name": "Colombia", "flag": "colombia.svg"},
    {"code": "KM", "name": "Comoros", "flag": "comoros.svg"},
    {"code": "CK", "name": "Cook Islands", "flag": "cook-islands.svg"},
    {"code": "CR", "name": "Costa Rica", "flag": "costa-rica.svg"},
    {"code": "CI", "name": "Côte d'Ivoire", "flag": "ivory-coast.svg"},
    {"code": "HR", "name": "Croatia", "flag": "croatia.svg"},
    {"code": "CU", "name": "Cuba", "flag": "cuba.svg"},
    {"code": "CW", "name": "Curaçao", "flag": "curacao.svg"},
    {"code": "CZ", "name": "Czech Republic", "flag": "czech-republic.svg"},
    {"code": "DK", "name": "Denmark", "flag": "denmark.svg"},
    {"code": "DJ", "name": "Djibouti", "flag": "djibouti.svg"},
    {"code": "DM", "name": "Dominica", "flag": "dominica.svg"},
    {"code": "DO", "name": "Dominican Republic", "flag": "dominican-republic.svg"},
    {"code": "EC", "name": "Ecuador", "flag": "ecuador.svg"},
    {"code": "EG", "name": "Egypt", "flag": "egypt.svg"},
    {"code": "SV", "name": "El Salvador", "flag": "el-salvador.svg"},
    {"code": "GQ", "name": "Equatorial Guinea", "flag": "equatorial-guinea.svg"},
    {"code": "ER", "name": "Eritrea", "flag": "eritrea.svg"},
    {"code": "EE", "name": "Estonia", "flag": "estonia.svg"},
    {"code": "ET", "name": "Ethiopia", "flag": "ethiopia.svg"},
    {"code": "FK", "name": "Falkland Islands (Malvinas)", "flag": "falkland-islands.svg"},
    {"code": "FJ", "name": "Fiji", "flag": "fiji.svg"},
    {"code": "FI", "name": "Finland", "flag": "finland.svg"},
    {"code": "FR", "name": "France", "flag": "france.svg"},
    {"code": "PF", "name": "French Polynesia", "flag": "french-polynesia.svg"},
    {"code": "GA", "name": "Gabon", "flag": "gabon.svg"},
    {"code": "GM", "name": "Gambia", "flag": "gambia.svg"},
    {"code": "GE", "name": "Georgia", "flag": "georgia.svg"},
    {"code": "DE", "name": "Germany", "flag": "germany.svg"},
    {"code": "GH", "name": "Ghana", "flag": "ghana.svg"},
    {"code": "GI", "name": "Gibraltar", "flag": "gibraltar.svg"},
    {"code": "GR", "name": "Greece", "flag": "greece.svg"},
    {"code": "GL", "name": "Greenland", "flag": "greenland.svg"},
    {"code": "GD", "name": "Grenada", "flag": "grenada.svg"},
    {"code": "GU", "name": "Guam", "flag": "guam.svg"},
    {"code": "GT", "name": "Guatemala", "flag": "guatemala.svg"},
    {"code": "GG", "name": "Guernsey", "flag": "guernsey.svg"},
    {"code": "GN", "name": "Guinea", "flag": "guinea.svg"},
    {"code": "GW", "name": "Guinea-Bissau", "flag": "guinea-bissau.svg"},
    {"code": "HT", "name": "Haiti", "flag": "haiti.svg"},
    {"code": "VA", "name": "Holy See (Vatican City State)", "flag": "vatican-city.svg"},
    {"code": "HN", "name": "Honduras", "flag": "honduras.svg"},
    {"code": "HK", "name": "Hong Kong", "flag": "hong-kong.svg"},
    {"code": "HU", "name": "Hungary", "flag": "hungary.svg"},
    {"code": "IS", "name": "Iceland", "flag": "iceland.svg"},
    {"code": "IN", "name": "India", "flag": "india.svg"},
    {"code": "ID", "name": "Indonesia", "flag": "indonesia.svg"},
    {"code": "IR", "name": "Iran, Islamic Republic of", "flag": "iran.svg"},
    {"code": "IQ", "name": "Iraq", "flag": "iraq.svg"},
    {"code": "IE", "name": "Ireland", "flag": "ireland.svg"},
    {"code": "IM", "name": "Isle of Man", "flag": "isle-of-man.svg"},
    {"code": "IL", "name": "Israel", "flag": "israel.svg"},
    {"code": "IT", "name": "Italy", "flag": "italy.svg"},
    {"code": "JM", "name": "Jamaica", "flag": "jamaica.svg"},
    {"code": "JP", "name": "Japan", "flag": "japan.svg"},
    {"code": "JE", "name": "Jersey", "flag": "jersey.svg"},
    {"code": "JO", "name": "Jordan", "flag": "jordan.svg"},
    {"code": "KZ", "name": "Kazakhstan", "flag": "kazakhstan.svg"},
    {"code": "KE", "name": "Kenya", "flag": "kenya.svg"},
    {"code": "KI", "name": "Kiribati", "flag": "kiribati.svg"},
    {"code": "KP", "name": "Korea, Democratic People's Republic of", "flag": "north-korea.svg"},
    {"code": "KR", "name": "South Korea", "flag": "south-korea.svg"},
    {"code": "KW", "name": "Kuwait", "flag": "kuwait.svg"},
    {"code": "KG", "name": "Kyrgyzstan", "flag": "kyrgyzstan.svg"},
    {"code": "LA", "name": "Lao People's Democratic Republic", "flag": "laos.svg"},
    {"code": "LV", "name": "Latvia", "flag": "latvia.svg"},
    {"code": "LB", "name": "Lebanon", "flag": "lebanon.svg"},
    {"code": "LS", "name": "Lesotho", "flag": "lesotho.svg"},
    {"code": "LR", "name": "Liberia", "flag": "liberia.svg"},
    {"code": "LY", "name": "Libya", "flag": "libya.svg"},
    {"code": "LI", "name": "Liechtenstein", "flag": "liechtenstein.svg"},
    {"code": "LT", "name": "Lithuania", "flag": "lithuania.svg"},
    {"code": "LU", "name": "Luxembourg", "flag": "luxembourg.svg"},
    {"code": "MO", "name": "Macao", "flag": "macao.svg"},
    {"code": "MG", "name": "Madagascar", "flag": "madagascar.svg"},
    {"code": "MW", "name": "Malawi", "flag": "malawi.svg"},
    {"code": "MY", "name": "Malaysia", "flag": "malaysia.svg"},
    {"code": "MV", "name": "Maldives", "flag": "maldives.svg"},
    {"code": "ML", "name": "Mali", "flag": "mali.svg"},
    {"code": "MT", "name": "Malta", "flag": "malta.svg"},
    {"code": "MH", "name": "Marshall Islands", "flag": "marshall-island.svg"},
    {"code": "MQ", "name": "Martinique", "flag": "martinique.svg"},
    {"code": "MR", "name": "Mauritania", "flag": "mauritania.svg"},
    {"code": "MU", "name": "Mauritius", "flag": "mauritius.svg"},
    {"code": "MX", "name": "Mexico", "flag": "mexico.svg"},
    {"code": "FM", "name": "Micronesia, Federated States of", "flag": "micronesia.svg"},
    {"code": "MD", "name": "Moldova, Republic of", "flag": "moldova.svg"},
    {"code": "MC", "name": "Monaco", "flag": "monaco.svg"},
    {"code": "MN", "name": "Mongolia", "flag": "mongolia.svg"},
    {"code": "ME", "name": "Montenegro", "flag": "montenegro.svg"},
    {"code": "MS", "name": "Montserrat", "flag": "montserrat.svg"},
    {"code": "MA", "name": "Morocco", "flag": "morocco.svg"},
    {"code": "MZ", "name": "Mozambique", "flag": "mozambique.svg"},
    {"code": "MM", "name": "Myanmar", "flag": "myanmar.svg"},
    {"code": "NA", "name": "Namibia", "flag": "namibia.svg"},
    {"code": "NR", "name": "Nauru", "flag": "nauru.svg"},
    {"code": "NP", "name": "Nepal", "flag": "nepal.svg"},
    {"code": "NL", "name": "Netherlands", "flag": "netherlands.svg"},
    {"code": "NZ", "name": "New Zealand", "flag": "new-zealand.svg"},
    {"code": "NI", "name": "Nicaragua", "flag": "nicaragua.svg"},
    {"code": "NE", "name": "Niger", "flag": "niger.svg"},
    {"code": "NG", "name": "Nigeria", "flag": "nigeria.svg"},
    {"code": "NU", "name": "Niue", "flag": "niue.svg"},
    {"code": "NF", "name": "Norfolk Island", "flag": "norfolk-island.svg"},
    {"code": "MP", "name": "Northern Mariana Islands", "flag": "northern-mariana-islands.svg"},
    {"code": "NO", "name": "Norway", "flag": "norway.svg"},
    {"code": "OM", "name": "Oman", "flag": "oman.svg"},
    {"code": "PK", "name": "Pakistan", "flag": "pakistan.svg"},
    {"code": "PW", "name": "Palau", "flag": "palau.svg"},
    {"code": "PS", "name": "Palestinian Territory, Occupied", "flag": "palestine.svg"},
    {"code": "PA", "name": "Panama", "flag": "panama.svg"},
    {"code": "PG", "name": "Papua New Guinea", "flag": "papua-new-guinea.svg"},
    {"code": "PY", "name": "Paraguay", "flag": "paraguay.svg"},
    {"code": "PE", "name": "Peru", "flag": "peru.svg"},
    {"code": "PH", "name": "Philippines", "flag": "philippines.svg"},
    {"code": "PL", "name": "Poland", "flag": "poland.svg"},
    {"code": "PT", "name": "Portugal", "flag": "portugal.svg"},
    {"code": "PR", "name": "Puerto Rico", "flag": "puerto-rico.svg"},
    {"code": "QA", "name": "Qatar", "flag": "qatar.svg"},
    {"code": "RO", "name": "Romania", "flag": "romania.svg"},
    {"code": "RU", "name": "Russian Federation", "flag": "russia.svg"},
    {"code": "RW", "name": "Rwanda", "flag": "rwanda.svg"},
    {"code": "BL", "name": "Saint Barthélemy", "flag": "st-barts.svg"},
    {"code": "KN", "name": "Saint Kitts and Nevis", "flag": "saint-kitts-and-nevis.svg"},
    {"code": "LC", "name": "Saint Lucia", "flag": "st-lucia.svg"},
    {"code": "MF", "name": "Saint Martin (French part)", "flag": "sint-maarten.svg"},
    {"code": "VC", "name": "Saint Vincent and the Grenadines", "flag": "st-vincent-and-the-grenadines.svg"},
    {"code": "WS", "name": "Samoa", "flag": "samoa.svg"},
    {"code": "SM", "name": "San Marino", "flag": "san-marino.svg"},
    {"code": "ST", "name": "Sao Tome and Principe", "flag": "sao-tome-and-prince.svg"},
    {"code": "SA", "name": "Saudi Arabia", "flag": "saudi-arabia.svg"},
    {"code": "SN", "name": "Senegal", "flag": "senegal.svg"},
    {"code": "RS", "name": "Serbia", "flag": "serbia.svg"},
    {"code": "SC", "name": "Seychelles", "flag": "seychelles.svg"},
    {"code": "SL", "name": "Sierra Leone", "flag": "sierra-leone.svg"},
    {"code": "SG", "name": "Singapore", "flag": "singapore.svg"},
    {"code": "SX", "name": "Sint Maarten (Dutch part)", "flag": "sint-maarten.svg"},
    {"code": "SK", "name": "Slovakia", "flag": "slovakia.svg"},
    {"code": "SI", "name": "Slovenia", "flag": "slovenia.svg"},
    {"code": "SB", "name": "Solomon Islands", "flag": "solomon-islands.svg"},
    {"code": "SO", "name": "Somalia", "flag": "somalia.svg"},
    {"code": "ZA", "name": "South Africa", "flag": "south-africa.svg"},
    {"code": "SS", "name": "South Sudan", "flag": "south-sudan.svg"},
    {"code": "ES", "name": "Spain", "flag": "spain.svg"},
    {"code": "LK", "name": "Sri Lanka", "flag": "sri-lanka.svg"},
    {"code": "SD", "name": "Sudan", "flag": "sudan.svg"},
    {"code": "SR", "name": "Suriname", "flag": "suriname.svg"},
    {"code": "SZ", "name": "Swaziland", "flag": "swaziland.svg"},
    {"code": "SE", "name": "Sweden", "flag": "sweden.svg"},
    {"code": "CH", "name": "Switzerland", "flag": "switzerland.svg"},
    {"code": "SY", "name": "Syrian Arab Republic", "flag": "syria.svg"},
    {"code": "TW", "name": "Taiwan, Province of China", "flag": "taiwan.svg"},
    {"code": "TJ", "name": "Tajikistan", "flag": "tajikistan.svg"},
    {"code": "TZ", "name": "Tanzania, United Republic of", "flag": "tanzania.svg"},
    {"code": "TH", "name": "Thailand", "flag": "thailand.svg"},
    {"code": "TG", "name": "Togo", "flag": "togo.svg"},
    {"code": "TK", "name": "Tokelau", "flag": "tokelau.svg"},
    {"code": "TO", "name": "Tonga", "flag": "tonga.svg"},
    {"code": "TT", "name": "Trinidad and Tobago", "flag": "trinidad-and-tobago.svg"},
    {"code": "TN", "name": "Tunisia", "flag": "tunisia.svg"},
    {"code": "TR", "name": "Turkey", "flag": "turkey.svg"},
    {"code": "TM", "name": "Turkmenistan", "flag": "turkmenistan.svg"},
    {"code": "TC", "name": "Turks and Caicos Islands", "flag": "turks-and-caicos.svg"},
    {"code": "TV", "name": "Tuvalu", "flag": "tuvalu.svg"},
    {"code": "UG", "name": "Uganda", "flag": "uganda.svg"},
    {"code": "UA", "name": "Ukraine", "flag": "ukraine.svg"},
    {"code": "AE", "name": "United Arab Emirates", "flag": "united-arab-emirates.svg"},
    {"code": "GB", "name": "United Kingdom", "flag": "united-kingdom.svg"},
    {"code": "US", "name": "United States", "flag": "united-states.svg"},
    {"code": "UY", "name": "Uruguay", "flag": "uruguay.svg"},
    {"code": "UZ", "name": "Uzbekistan", "flag": "uzbekistan.svg"},
    {"code": "VU", "name": "Vanuatu", "flag": "vanuatu.svg"},
    {"code": "VE", "name": "Venezuela, Bolivarian Republic of", "flag": "venezuela.svg"},
    {"code": "VN", "name": "Vietnam", "flag": "vietnam.svg"},
    {"code": "VI", "name": "Virgin Islands", "flag": "virgin-islands.svg"},
    {"code": "YE", "name": "Yemen", "flag": "yemen.svg"},
    {"code": "ZM", "name": "Zambia", "flag": "zambia.svg"},
    {"code": "ZW", "name": "Zimbabwe", "flag": "zimbabwe.svg"},
]

LANGUAGES_DATA = [
    {"code": "id", "name": "Bahasa Indonesia - Indonesian", "flag": "indonesia.svg"},
    {"code": "msa", "name": "Bahasa Melayu - Malay", "flag": "malaysia.svg"},
    {"code": "ca", "name": "Català - Catalan", "flag": "canada.svg"},
    {"code": "cs", "name": "Čeština - Czech", "flag": "czech-republic.svg"},
    {"code": "da", "name": "Dansk - Danish", "flag": "netherlands.svg"},
    {"code": "de", "name": "Deutsch - German", "flag": "germany.svg"},
    {"code": "en", "name": "English", "flag": "united-kingdom.svg"},
    {"code": "en-gb", "name": "English UK - British English", "flag": "united-kingdom.svg"},
    {"code": "es", "name": "Español - Spanish", "flag": "spain.svg"},
    {"code": "fil", "name": "Filipino", "flag": "philippines.svg"},
    {"code": "fr", "name": "Français - French", "flag": "france.svg"},
    {"code": "ga", "name": "Gaeilge - Irish (beta)", "flag": "gabon.svg"},
    {"code": "gl", "name": "Galego - Galician (beta)", "flag": "greenland.svg"},
    {"code": "hr", "name": "Hrvatski - Croatian", "flag": "croatia.svg"},
    {"code": "it", "name": "Italiano - Italian", "flag": "italy.svg"},
    {"code": "hu", "name": "Magyar - Hungarian", "flag": "hungary.svg"},
    {"code": "nl", "name": "Nederlands - Dutch", "flag": "netherlands.svg"},
    {"code": "no", "name": "Norsk - Norwegian", "flag": "norway.svg"},
    {"code": "pl", "name": "Polski - Polish", "flag": "poland.svg"},
    {"code": "pt", "name": "Português - Portuguese", "flag": "portugal.svg"},
    {"code": "ro", "name": "Română - Romanian", "flag": "romania.svg"},
    {"code": "sk", "name": "Slovenčina - Slovak", "flag": "slovakia.svg"},
    {"code": "fi", "name": "Suomi - Finnish", "flag": "finland.svg"},
    {"code": "sv", "name": "Svenska - Swedish", "flag": "el-salvador.svg"},
    {"code": "vi", "name": "Tiếng Việt - Vietnamese", "flag": "virgin-islands.svg"},
    {"code": "tr", "name": "Türkçe - Turkish", "flag": "turkey.svg"},
    {"code": "el", "name": "Ελληνικά - Greek", "flag": "greece.svg"},
    {"code": "bg", "name": "Български език - Bulgarian", "flag": "bulgaria.svg"},
    {"code": "ru", "name": "Русский - Russian", "flag": "russia.svg"},
    {"code": "sr", "name": "Српски - Serbian", "flag": "suriname.svg"},
    {"code": "uk", "name": "Українська мова - Ukrainian", "flag": "ukraine.svg"},
    {"code": "he", "name": "עִבְרִית - Hebrew", "flag": "israel.svg"},
    {"code": "ur", "name": "اردو - Urdu (beta)", "flag": "pakistan.svg"},
    {"code": "ar", "name": "العربية - Arabic", "flag": "argentina.svg"},
    {"code": "fa", "name": "فارسی - Persian", "flag": "argentina.svg"},
    {"code": "mr", "name": "मराठी - Marathi", "flag": "mauritania.svg"},
    {"code": "hi", "name": "हिन्दी - Hindi", "flag": "india.svg"},
    {"code": "bn", "name": "বাংলা - Bangla", "flag": "bangladesh.svg"},
    {"code": "gu", "name": "ગુજરાતી - Gujarati", "flag": "guam.svg"},
    {"code": "ta", "name": "தமிழ் - Tamil", "flag": "india.svg"},
    {"code": "kn", "name": "ಕನ್ನಡ - Kannada", "flag": "saint-kitts-and-nevis.svg"},
    {"code": "th", "name": "ภาษาไทย - Thai", "flag": "thailand.svg"},
    {"code": "ko", "name": "한국어 - Korean", "flag": "south-korea.svg"},
    {"code": "ja", "name": "日本語 - Japanese", "flag": "japan.svg"},
    {"code": "zh-cn", "name": "简体中文 - Simplified Chinese", "flag": "china.svg"},
    {"code": "zh-tw", "name": "繁體中文 - Traditional Chinese", "flag": "taiwan.svg"},
]

TIMEZONES_DATA = [
    {"value": "International Date Line West", "name": "(GMT-11:00) International Date Line West", "offset": "-39600"},
    {"value": "Midway Island", "name": "(GMT-11:00) Midway Island", "offset": "-39600"},
    {"value": "Samoa", "name": "(GMT-11:00) Samoa", "offset": "-39600"},
    {"value": "Hawaii", "name": "(GMT-10:00) Hawaii", "offset": "-36000"},
    {"value": "Alaska", "name": "(GMT-08:00) Alaska", "offset": "-28800"},
    {"value": "Pacific Time (US & Canada)", "name": "(GMT-07:00) Pacific Time (US & Canada)", "offset": "-25200"},
    {"value": "Tijuana", "name": "(GMT-07:00) Tijuana", "offset": "-25200"},
    {"value": "Arizona", "name": "(GMT-07:00) Arizona", "offset": "-25200"},
    {"value": "Mountain Time (US & Canada)", "name": "(GMT-06:00) Mountain Time (US & Canada)", "offset": "-21600"},
    {"value": "Chihuahua", "name": "(GMT-06:00) Chihuahua", "offset": "-21600"},
    {"value": "Mazatlan", "name": "(GMT-06:00) Mazatlan", "offset": "-21600"},
    {"value": "Saskatchewan", "name": "(GMT-06:00) Saskatchewan", "offset": "-21600"},
    {"value": "Central America", "name": "(GMT-06:00) Central America", "offset": "-21600"},
    {"value": "Central Time (US & Canada)", "name": "(GMT-05:00) Central Time (US & Canada)", "offset": "-18000"},
    {"value": "Guadalajara", "name": "(GMT-05:00) Guadalajara", "offset": "-18000"},
    {"value": "Mexico City", "name": "(GMT-05:00) Mexico City", "offset": "-18000"},
    {"value": "Monterrey", "name": "(GMT-05:00) Monterrey", "offset": "-18000"},
    {"value": "Bogota", "name": "(GMT-05:00) Bogota", "offset": "-18000"},
    {"value": "Lima", "name": "(GMT-05:00) Lima", "offset": "-18000"},
    {"value": "Quito", "name": "(GMT-05:00) Quito", "offset": "-18000"},
    {"value": "Eastern Time (US & Canada)", "name": "(GMT-04:00) Eastern Time (US & Canada)", "offset": "-14400"},
    {"value": "Indiana (East)", "name": "(GMT-04:00) Indiana (East)", "offset": "-14400"},
    {"value": "Caracas", "name": "(GMT-04:00) Caracas", "offset": "-14400"},
    {"value": "La Paz", "name": "(GMT-04:00) La Paz", "offset": "-14400"},
    {"value": "Georgetown", "name": "(GMT-04:00) Georgetown", "offset": "-14400"},
    {"value": "Atlantic Time (Canada)", "name": "(GMT-03:00) Atlantic Time (Canada)", "offset": "-10800"},
    {"value": "Santiago", "name": "(GMT-03:00) Santiago", "offset": "-10800"},
    {"value": "Brasilia", "name": "(GMT-03:00) Brasilia", "offset": "-10800"},
    {"value": "Buenos Aires", "name": "(GMT-03:00) Buenos Aires", "offset": "-10800"},
    {"value": "Newfoundland", "name": "(GMT-02:30) Newfoundland", "offset": "-9000"},
    {"value": "Greenland", "name": "(GMT-02:00) Greenland", "offset": "-7200"},
    {"value": "Mid-Atlantic", "name": "(GMT-02:00) Mid-Atlantic", "offset": "-7200"},
    {"value": "Cape Verde Is.", "name": "(GMT-01:00) Cape Verde Is.", "offset": "-3600"},
    {"value": "Azores", "name": "(GMT) Azores", "offset": "0"},
    {"value": "Monrovia", "name": "(GMT) Monrovia", "offset": "0"},
    {"value": "UTC", "name": "(GMT) UTC", "offset": "0"},
    {"value": "Dublin", "name": "(GMT+01:00) Dublin", "offset": "3600"},
    {"value": "Edinburgh", "name": "(GMT+01:00) Edinburgh", "offset": "3600"},
    {"value": "Lisbon", "name": "(GMT+01:00) Lisbon", "offset": "3600"},
    {"value": "London", "name": "(GMT+01:00) London", "offset": "3600"},
    {"value": "Casablanca", "name": "(GMT+01:00) Casablanca", "offset": "3600"},
    {"value": "West Central Africa", "name": "(GMT+01:00) West Central Africa", "offset": "3600"},
    {"value": "Belgrade", "name": "(GMT+02:00) Belgrade", "offset": "7200"},
    {"value": "Bratislava", "name": "(GMT+02:00) Bratislava", "offset": "7200"},
    {"value": "Budapest", "name": "(GMT+02:00) Budapest", "offset": "7200"},
    {"value": "Ljubljana", "name": "(GMT+02:00) Ljubljana", "offset": "7200"},
    {"value": "Prague", "name": "(GMT+02:00) Prague", "offset": "7200"},
    {"value": "Sarajevo", "name": "(GMT+02:00) Sarajevo", "offset": "7200"},
    {"value": "Skopje", "name": "(GMT+02:00) Skopje", "offset": "7200"},
    {"value": "Warsaw", "name": "(GMT+02:00) Warsaw", "offset": "7200"},
    {"value": "Zagreb", "name": "(GMT+02:00) Zagreb", "offset": "7200"},
    {"value": "Brussels", "name": "(GMT+02:00) Brussels", "offset": "7200"},
    {"value": "Copenhagen", "name": "(GMT+02:00) Copenhagen", "offset": "7200"},
    {"value": "Madrid", "name": "(GMT+02:00) Madrid", "offset": "7200"},
    {"value": "Paris", "name": "(GMT+02:00) Paris", "offset": "7200"},
    {"value": "Amsterdam", "name": "(GMT+02:00) Amsterdam", "offset": "7200"},
    {"value": "Berlin", "name": "(GMT+02:00) Berlin", "offset": "7200"},
    {"value": "Bern", "name": "(GMT+02:00) Bern", "offset": "7200"},
    {"value": "Rome", "name": "(GMT+02:00) Rome", "offset": "7200"},
    {"value": "Stockholm", "name": "(GMT+02:00) Stockholm", "offset": "7200"},
    {"value": "Vienna", "name": "(GMT+02:00) Vienna", "offset": "7200"},
    {"value": "Cairo", "name": "(GMT+02:00) Cairo", "offset": "7200"},
    {"value": "Harare", "name": "(GMT+02:00) Harare", "offset": "7200"},
    {"value": "Pretoria", "name": "(GMT+02:00) Pretoria", "offset": "7200"},
    {"value": "Bucharest", "name": "(GMT+03:00) Bucharest", "offset": "10800"},
    {"value": "Helsinki", "name": "(GMT+03:00) Helsinki", "offset": "10800"},
    {"value": "Kiev", "name": "(GMT+03:00) Kiev", "offset": "10800"},
    {"value": "Kyiv", "name": "(GMT+03:00) Kyiv", "offset": "10800"},
    {"value": "Riga", "name": "(GMT+03:00) Riga", "offset": "10800"},
    {"value": "Sofia", "name": "(GMT+03:00) Sofia", "offset": "10800"},
    {"value": "Tallinn", "name": "(GMT+03:00) Tallinn", "offset": "10800"},
    {"value": "Vilnius", "name": "(GMT+03:00) Vilnius", "offset": "10800"},
    {"value": "Athens", "name": "(GMT+03:00) Athens", "offset": "10800"},
    {"value": "Istanbul", "name": "(GMT+03:00) Istanbul", "offset": "10800"},
    {"value": "Minsk", "name": "(GMT+03:00) Minsk", "offset": "10800"},
    {"value": "Jerusalem", "name": "(GMT+03:00) Jerusalem", "offset": "10800"},
    {"value": "Moscow", "name": "(GMT+03:00) Moscow", "offset": "10800"},
    {"value": "St. Petersburg", "name": "(GMT+03:00) St. Petersburg", "offset": "10800"},
    {"value": "Volgograd", "name": "(GMT+03:00) Volgograd", "offset": "10800"},
    {"value": "Kuwait", "name": "(GMT+03:00) Kuwait", "offset": "10800"},
    {"value": "Riyadh", "name": "(GMT+03:00) Riyadh", "offset": "10800"},
    {"value": "Nairobi", "name": "(GMT+03:00) Nairobi", "offset": "10800"},
    {"value": "Baghdad", "name": "(GMT+03:00) Baghdad", "offset": "10800"},
    {"value": "Abu Dhabi", "name": "(GMT+04:00) Abu Dhabi", "offset": "14400"},
    {"value": "Muscat", "name": "(GMT+04:00) Muscat", "offset": "14400"},
    {"value": "Baku", "name": "(GMT+04:00) Baku", "offset": "14400"},
    {"value": "Tbilisi", "name": "(GMT+04:00) Tbilisi", "offset": "14400"},
    {"value": "Yerevan", "name": "(GMT+04:00) Yerevan", "offset": "14400"},
    {"value": "Tehran", "name": "(GMT+04:30) Tehran", "offset": "16200"},
    {"value": "Kabul", "name": "(GMT+04:30) Kabul", "offset": "16200"},
    {"value": "Ekaterinburg", "name": "(GMT+05:00) Ekaterinburg", "offset": "18000"},
    {"value": "Islamabad", "name": "(GMT+05:00) Islamabad", "offset": "18000"},
    {"value": "Karachi", "name": "(GMT+05:00) Karachi", "offset": "18000"},
    {"value": "Tashkent", "name": "(GMT+05:00) Tashkent", "offset": "18000"},
    {"value": "Chennai", "name": "(GMT+05:30) Chennai", "offset": "19800"},
    {"value": "Kolkata", "name": "(GMT+05:30) Kolkata", "offset": "19800"},
    {"value": "Mumbai", "name": "(GMT+05:30) Mumbai", "offset": "19800"},
    {"value": "New Delhi", "name": "(GMT+05:30) New Delhi", "offset": "19800"},
    {"value": "Sri Jayawardenepura", "name": "(GMT+05:30) Sri Jayawardenepura", "offset": "19800"},
    {"value": "Kathmandu", "name": "(GMT+05:45) Kathmandu", "offset": "20700"},
    {"value": "Astana", "name": "(GMT+06:00) Astana", "offset": "21600"},
    {"value": "Dhaka", "name": "(GMT+06:00) Dhaka", "offset": "21600"},
    {"value": "Almaty", "name": "(GMT+06:00) Almaty", "offset": "21600"},
    {"value": "Urumqi", "name": "(GMT+06:00) Urumqi", "offset": "21600"},
    {"value": "Rangoon", "name": "(GMT+06:30) Rangoon", "offset": "23400"},
    {"value": "Novosibirsk", "name": "(GMT+07:00) Novosibirsk", "offset": "25200"},
    {"value": "Bangkok", "name": "(GMT+07:00) Bangkok", "offset": "25200"},
    {"value": "Hanoi", "name": "(GMT+07:00) Hanoi", "offset": "25200"},
    {"value": "Jakarta", "name": "(GMT+07:00) Jakarta", "offset": "25200"},
    {"value": "Krasnoyarsk", "name": "(GMT+07:00) Krasnoyarsk", "offset": "25200"},
    {"value": "Beijing", "name": "(GMT+08:00) Beijing", "offset": "28800"},
    {"value": "Chongqing", "name": "(GMT+08:00) Chongqing", "offset": "28800"},
    {"value": "Hong Kong", "name": "(GMT+08:00) Hong Kong", "offset": "28800"},
    {"value": "Kuala Lumpur", "name": "(GMT+08:00) Kuala Lumpur", "offset": "28800"},
    {"value": "Singapore", "name": "(GMT+08:00) Singapore", "offset": "28800"},
    {"value": "Taipei", "name": "(GMT+08:00) Taipei", "offset": "28800"},
    {"value": "Perth", "name": "(GMT+08:00) Perth", "offset": "28800"},
    {"value": "Irkutsk", "name": "(GMT+08:00) Irkutsk", "offset": "28800"},
    {"value": "Ulaan Bataar", "name": "(GMT+08:00) Ulaan Bataar", "offset": "28800"},
    {"value": "Seoul", "name": "(GMT+09:00) Seoul", "offset": "32400"},
    {"value": "Osaka", "name": "(GMT+09:00) Osaka", "offset": "32400"},
    {"value": "Sapporo", "name": "(GMT+09:00) Sapporo", "offset": "32400"},
    {"value": "Tokyo", "name": "(GMT+09:00) Tokyo", "offset": "32400"},
    {"value": "Yakutsk", "name": "(GMT+09:00) Yakutsk", "offset": "32400"},
    {"value": "Darwin", "name": "(GMT+09:30) Darwin", "offset": "34200"},
    {"value": "Adelaide", "name": "(GMT+09:30) Adelaide", "offset": "34200"},
    {"value": "Canberra", "name": "(GMT+10:00) Canberra", "offset": "36000"},
    {"value": "Melbourne", "name": "(GMT+10:00) Melbourne", "offset": "36000"},
    {"value": "Sydney", "name": "(GMT+10:00) Sydney", "offset": "36000"},
    {"value": "Brisbane", "name": "(GMT+10:00) Brisbane", "offset": "36000"},
    {"value": "Hobart", "name": "(GMT+10:00) Hobart", "offset": "36000"},
    {"value": "Vladivostok", "name": "(GMT+10:00) Vladivostok", "offset": "36000"},
    {"value": "Guam", "name": "(GMT+10:00) Guam", "offset": "36000"},
    {"value": "Port Moresby", "name": "(GMT+10:00) Port Moresby", "offset": "36000"},
    {"value": "Solomon Is.", "name": "(GMT+10:00) Solomon Is.", "offset": "36000"},
    {"value": "Magadan", "name": "(GMT+11:00) Magadan", "offset": "39600"},
    {"value": "New Caledonia", "name": "(GMT+11:00) New Caledonia", "offset": "39600"},
    {"value": "Fiji", "name": "(GMT+12:00) Fiji", "offset": "43200"},
    {"value": "Kamchatka", "name": "(GMT+12:00) Kamchatka", "offset": "43200"},
    {"value": "Marshall Is.", "name": "(GMT+12:00) Marshall Is.", "offset": "43200"},
    {"value": "Auckland", "name": "(GMT+12:00) Auckland", "offset": "43200"},
    {"value": "Wellington", "name": "(GMT+12:00) Wellington", "offset": "43200"},
    {"value": "Nuku'alofa", "name": "(GMT+13:00) Nuku'alofa", "offset": "46800"},
]

CURRENCIES_DATA = [
    {"code": "USD", "name": "USD - USA dollar", "flag": "united-states.svg"},
    {"code": "GBP", "name": "GBP - British pound", "flag": "united-kingdom.svg"},
    {"code": "AUD", "name": "AUD - Australian dollar", "flag": "australia.svg"},
    {"code": "JPY", "name": "JPY - Japanese yen", "flag": "japan.svg"},
    {"code": "SEK", "name": "SEK - Swedish krona", "flag": "sweden.svg"},
    {"code": "CAD", "name": "CAD - Canadian dollar", "flag": "canada.svg"},
    {"code": "CHF", "name": "CHF - Swiss franc", "flag": "switzerland.svg"},
]